locallibrary/catalog/urls.py
# urls de nuestra aplicación catalogo
from django.urls import path
from .views import index, acerca_de, BookListView, BookDetailView, \
        SearchResultsListView, LibrosPrestados, renovar_libro, \
        AuthorCreate, AuthorUpdate, AuthorDelete, AuthorListView, \
        BookUpdateView
    

urlpatterns = [
    path('', index, name='index'),
    path('acerca-de/', acerca_de, name='acercade'),
    path('libros/', BookListView.as_view(), name='lista-libros'),
    path('libros/<int:pk>', BookDetailView.as_view(), name='detalle-libro'),
    path('libros/<int:pk>/update', BookUpdateView.as_view(), name='editar-libro'),
    path('busqueda/', SearchResultsListView.as_view(), name='buscar'),
    path('prestados/', LibrosPrestados.as_view(), name='prestados'),
    path('libro/<uuid:pk>/renovar/', renovar_libro, name='renovar-fecha'),
    path('autores/', AuthorListView.as_view(), name='autores'),
    path('autores/create/', AuthorCreate.as_view(), name='author-create'),
    path('autores/<int:pk>/update/', AuthorUpdate.as_view(), name='author-update'),
    path('autores/<int:pk>/delete/', AuthorDelete.as_view(), name='author-delete'),


]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# importamos la vista de nuestra app catalog
from catalog.views import index_general

urlpatterns = [
    path('admin/', admin.site.urls),
    # castellanizar url catálogo
    path("select2/", include("django_select2.urls")),
    path('catalogo/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 

    # para el index general
    path('', index_general, name='index_general'),

    # urls de django-debug-toolbar
    path('__debug__/', include('debug_toolbar.urls')),
    
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locallibrary/catalog/models.py
from django.db import models
import uuid
from django.utils.translation import gettext_lazy as _
from django.contrib import admin
from django.utils.html import format_html


# https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models
# Create your models here.


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author',
                               on_delete=models.SET_NULL,  # que pasa si borramos el autor?
                               null=True)  # puede ser nulo?
    summary = models.TextField(
        max_length=1000,
        help_text='Enter a brief description of the book',
        blank=True)
    isbn = models.CharField(
        'ISBN',
        max_length=13,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField('Genre',
                                   help_text='Select a genre for this book')

    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    class Meta:
        verbose_name = _('Book')
        verbose_name_plural = _('Books')
        ordering = ['title']


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=180,
                            help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        # ordering = ['last_name', 'first_name']
        ordering = ['last_name', 'first_name']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book',
                             on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200, blank=True)
    due_back = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to='images', blank=True, null=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} - {self.book.title}'

    @admin.display(description=_("Image"))
    def img_image(self):
        if self.image:
            return format_html(
                '<img src="{}" width="80" />'.format(
                    self.image.url)
            )
        else:
            return ''

    @admin.display(description=_("Status"))
    def status_color(self):
        return format_html(
            '<span style="color:{}; font-size:18px;">📗</span>',
            'green' if self.status == 'a' else 'red'
        )

locallibrary/catalog/forms.py
# archivo forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from catalog.models import BookInstance, Book
from django_select2 import forms as s2forms


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text=_(
        "Enter a date between now and 4 weeks (default 3)."))

    def clean_renewal_date(self):
        '''Valida que la fecha no sea en el pasado y no más de 4 semanas en el futuro'''
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

# Ahora el mismo formulario con un modelForm


class RenewBookModelForm(forms.ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = BookInstance
        fields = ['due_back', 'status']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _(
            'Enter a date between now and 4 weeks (default 3).')}


class ContactForm(forms.Form):
    ''' Contact form '''
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)
    from_email.widget.attrs.update({'class': 'form-control'})
    subject.widget.attrs.update({'class': 'form-control'})
    message.widget.attrs.update({'class': 'form-control'})


class AutorWidget(s2forms.ModelSelect2Widget):
    search_fields = ['first_name__icontains', 'last_name__icontains']


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'isbn', 'summary', 'genre', 'language']
        widgets = {
            'author': AutorWidget, # 'select2'
        }

locallibrary/catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from catalog.models import Book, BookInstance, Author
from django.views.generic import ListView, DetailView
import datetime
from catalog.forms import RenewBookForm, RenewBookModelForm
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from catalog.forms import ContactForm, BookForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.


def index_general(request):

    return render(request, 'index-general.html')


def acerca_de(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            messages.success(request, 'Message sent successfully!')
            return HttpResponseRedirect(reverse('index'))
        messages.error(request, "Error. Message not sent.")

    context = {}
    context['title'] = 'Acerca de'
    context['coords'] = '41.656771,-0.8960287'  # "41.6447242,-0.9231553"
    context['form'] = ContactForm()

    return render(request, 'catalog/acerca_de.html', context)


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    ultimos = Book.objects.all().order_by('-id')[:10]

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={
            'num_books': num_books,
            'num_instances': num_instances,
            'num_instances_available': num_instances_available,
            'num_authors': num_authors,
            'num_visits': num_visits,
            'ultimos': ultimos},
    )


# Listas Genéricas
class BookListView(ListView):
    '''Vista genérica para el listado de libros'''
    model = Book
    paginate_by = 15

    def get_queryset(self):
        return Book.objects.all().order_by('title')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['ahora'] = datetime.datetime.now()
        return context


class BookDetailView(DetailView):
    '''Vista genérica para el detalle de un libro'''
    model = Book

# Búsqueda


class SearchResultsListView(ListView):
    model = Book

    def get_queryset(self):  # new
        query = self.request.GET.get('q', '')
        # voy a guardar query para el contexto
        if query:
            self.query = query
            resultado = Book.objects.filter(title__icontains=query)
            # ampliar búsqueda y concatenar resultados
            return resultado

        else:
            return []

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(SearchResultsListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['busqueda'] = self.query
        context['anterior'] = self.request.META.get('HTTP_REFERER')
        return context


class LibrosPrestados(ListView):
    '''Vista genérica para el listado de libros que han sido prestados'''
    model = BookInstance
    template_name = 'catalog/libros_prestados.html'
    paginate_by = 15

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('-due_back')


# Vista para renovar un libro
def renovar_libro(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookModelForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['due_back']
            book_instance.status = form.cleaned_data['status']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('prestados'))

    # If this is a GET (or any other method) create the default form.
    else:

        # inicializa la fecha de renovación dentro de 3 semanas
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm(initial={'due_back': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/renovacion_fecha.html', context)


# Gestión de autores con vistas genéricas

class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    # Si funciona bien: success_url
    success_url = reverse_lazy('autores')
    #initial = {'date_of_death': '11/06/2020'}


class AuthorUpdate(UpdateView):
    model = Author
    # Not recommended (potential security issue if more fields added)
    fields = '__all__'
    success_url = reverse_lazy('autores')


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('autores')


class AuthorListView(ListView):
    model = Author
    paginate_by = 15

    def get_queryset(self):
        return Author.objects.all().order_by('last_name')


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    # Not recommended (potential security issue if more fields added)
    
    success_url = reverse_lazy('detalle-libro')

locallibrary/catalog/templates/catalog/acerca_de.html
{% extends "base.html" %} 


{% block title %} {{ title }} 
{% endblock %} 

{% block extracss %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>

<style>
    #map { height: 400px ;}
</style>
{% endblock %}

{% block content %}
<h1 class="my-4 text-center">{{ title }}</h1>
<div class="row">
    <div class="col-md-6">
        <div id="map"></div>
    </div>
    <div class="col-md-6">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <div class="form-actions">
        <button  class="btn btn-primary" type="submit">Send</button>
    </div>
</form>
    </div>
</div>
{% endblock %}

{% block extrajs %}
 
 <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>

<script>
    var mimapa = L.map('map').setView([{{coords}}], 13);

    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>',
    maxZoom: 18
    }).addTo(mimapa);

    L.marker([{{coords}}]).addTo(mimapa).bindPopup("CPI Los Enlaces");
</script>


{% endblock %}  

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <p>Are you sure you want to delete this author?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm" />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>{% trans "Author" %}</h1>

  <form action="" method="post">
    {% csrf_token %} <!-- #  Atención!! Protección CSRF-->
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends 'base.html' %}

{% block title %}Listado de autores{% endblock %}


{% block content %}
    <div class="row my-4">
    <h1 class="col-6">Listado de autores</h1>
    <h1 class="col-6"><form class="d-flex" action="{% url 'buscar' %}">
          <input class="form-control me-sm-2" type="text" 
              name="q" placeholder="Buscar autor" 
              required >
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Buscar</button>
        </form></h1>
    </div>

<ul class="list-group container">
{% for autor in author_list %}

<li class="list-group-item">
    <div class="row">
    <div class="col-6">{{autor}}</div> 
    <div class="col-2"><a href="{% url 'author-update' autor.id %}"><i class="bi bi-pencil-square"></i></a></div>
    <div class="col-2"><a href="{% url 'author-delete' autor.id %}"><i class="bi bi-trash"></i></a></div>
    </div>
</li>
{% empty %}
<div > No hemos encontrado ningún libro con la búsqueda <strong>{{busqueda}}</strong></li>
{% endfor %}
</ul>

<i class="bi bi-pencil-square"></i>
    {% if is_paginated %}
    
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

  
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends 'base.html' %}

{% block title %}Detalle de libro{% endblock %}

{% block content %}
    <h1>{{ book.title }}  <a href="{% url 'editar-libro' book.id %}"><i class="bi bi-pencil"></i></a></h1> 
<p>Título: {{ book.title }}</p>
<p>Autor: {{ book.author }}</p>
<p>Resumen: {{ book.summary }}</p>
<p>ISBN: {{ book.isbn }}</p>

Ejemplares: {{ book.bookinstance_set.all.count }}

{% for b in book.bookinstance_set.all %}
    {{b.status}} &nbsp;
{% endfor %}

{% endblock %}

locallibrary/catalog/templates/catalog/book_form.html
{% extends "base.html" %}
{% load i18n  django_bootstrap5 %}

{% block extracss %}
{{ form.media.css }}
{% endblock %}

{% block content %}
<h1>{% trans "Book" %}</h1>

  <form action="" method="post">
    {% csrf_token %} <!-- #  Atención!! Protección CSRF-->
    <table>
    {% bootstrap_form form %}
  
    </table>
    <input type="submit" class="form-control" value="Submit" />
  </form>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  {{ form.media.js }}
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends 'base.html' %}

{% block title %}Listado de libros{% endblock %}


{% block content %}
    <h1>Listado de libros</h1>
<h2>{{ ahora }}</h2>
{% if anterior %}
<a href="{{ anterior }}">Volver</a>
{% endif %}

    <ul class="list-group">
    {% for libro in book_list %}

<li class="list-group-item"><a href="{% url 'detalle-libro' libro.id  %}">{{ libro }}</a></li>
{% empty %}
<li> No hemos encontrado ningún libro con la búsqueda <strong>{{busqueda}}</strong></li>
    {% endfor %}
</ul>


    {% if is_paginated %}
    
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

  
{% endblock %}

locallibrary/catalog/templates/catalog/libros_prestados.html
{% extends 'base.html' %}

{% block title %}Listado de libros prestados{% endblock %}


{% block content %}
    <h1>Libros prestados</h1>

    <ul class="list-group">
    {% for libro in bookinstance_list %}

<li class="list-group-item">{{ libro.book.title }} - {{ libro.due_back }} -->

    <a href="{% url 'renovar-fecha' libro.id %}"> modificar fecha </a></li>
    {% endfor %}
</ul>


    {% if is_paginated %}
    
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

  
{% endblock %}

locallibrary/catalog/templates/catalog/renovacion_fecha.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% get_current_language as LANGUAGE_CODE %}
Current language: {{ LANGUAGE_CODE }}

  <h1>Renovar libro</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Renovar" />
  </form>
{% endblock %}